// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM24BaB0lyPYQokaorkZfylMSsrZEddKM',
    appId: '1:173913137859:web:1841b66e3eb6997b797876',
    messagingSenderId: '173913137859',
    projectId: 'chatty-app-4bf4b',
    authDomain: 'chatty-app-4bf4b.firebaseapp.com',
    storageBucket: 'chatty-app-4bf4b.firebasestorage.app',
    measurementId: 'G-6PS307N0FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM0Gw96bZtKoYPWhC9XRmIWiifFr5hTA4',
    appId: '1:173913137859:android:fbeb149a53405529797876',
    messagingSenderId: '173913137859',
    projectId: 'chatty-app-4bf4b',
    storageBucket: 'chatty-app-4bf4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPjMSmL5ApZxYRnxQKZURFaOio69onSV4',
    appId: '1:173913137859:ios:cc66157bd3aa3dc5797876',
    messagingSenderId: '173913137859',
    projectId: 'chatty-app-4bf4b',
    storageBucket: 'chatty-app-4bf4b.firebasestorage.app',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPjMSmL5ApZxYRnxQKZURFaOio69onSV4',
    appId: '1:173913137859:ios:cc66157bd3aa3dc5797876',
    messagingSenderId: '173913137859',
    projectId: 'chatty-app-4bf4b',
    storageBucket: 'chatty-app-4bf4b.firebasestorage.app',
    iosBundleId: 'com.example.chatty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM24BaB0lyPYQokaorkZfylMSsrZEddKM',
    appId: '1:173913137859:web:b1b3a037192cce20797876',
    messagingSenderId: '173913137859',
    projectId: 'chatty-app-4bf4b',
    authDomain: 'chatty-app-4bf4b.firebaseapp.com',
    storageBucket: 'chatty-app-4bf4b.firebasestorage.app',
    measurementId: 'G-2Q25N5C1C4',
  );
}
